purgers:
  -
    instance_id: 59aef30af1
    plugin_id: varnish
    order_index: 2
processors:
  -
    plugin_id: drush_purge_invalidate
    status: false
  -
    plugin_id: drush_purge_queue_work
    status: true
  -
    plugin_id: cron
    status: true
  -
    plugin_id: purge_ui_block_processor
    status: true
